<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $report->title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .logo {
            max-width: 200px;
            margin: 0 auto 20px;
        }
        .report-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
            color: #2563eb;
        }
        .project-info {
            font-size: 16px;
            color: #666;
            margin-bottom: 20px;
        }
        .description {
            margin-bottom: 30px;
            padding: 15px;
            background-color: #f3f4f6;
            border-radius: 5px;
        }
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .section-title {
            font-size: 20px;
            font-weight: bold;
            color: #1f2937;
            margin-bottom: 15px;
            padding-bottom: 5px;
            border-bottom: 2px solid #e5e7eb;
        }
        .section-content {
            margin-bottom: 15px;
        }
        .section-image {
            max-width: 100%;
            margin: 15px 0;
        }
        .seo-logs {
            margin-top: 30px;
        }
        .seo-log {
            margin-bottom: 20px;
            padding: 15px;
            background-color: #f9fafb;
            border-left: 4px solid #2563eb;
        }
        .seo-log-title {
            font-weight: bold;
            color: #1f2937;
            margin-bottom: 5px;
        }
        .seo-log-meta {
            font-size: 14px;
            color: #6b7280;
            margin-bottom: 10px;
        }
        .page-break {
            page-break-after: always;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th, td {
            border: 1px solid #e5e7eb;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        @if($report->project->logo_path)
            <img src="{{ Storage::url($report->project->logo_path) }}" alt="Project Logo" class="logo">
        @endif
        <h1 class="report-title">{{ $report->title }}</h1>
        <div class="project-info">
            <p>Project: {{ $report->project->name }}</p>
            <p>Generated: {{ $report->generated_at->format('F j, Y') }}</p>
            <p>Generated By: {{ $report->generator->name }}</p>
        </div>
    </div>

    <div class="description">
        {!! $report->description['content'] ?? '' !!}
    </div>

    @foreach($report->sections as $section)
        <div class="section">
            <h2 class="section-title">{{ $section->title }}</h2>
            <div class="section-content">
                {!! $section->content['content'] ?? '' !!}
            </div>
            @if($section->image_path)
                <img src="{{ Storage::url($section->image_path) }}" 
                     alt="{{ $section->title }}" 
                     class="section-image">
            @endif
        </div>
        @if(!$loop->last)
            <div class="page-break"></div>
        @endif
    @endforeach

    @if($report->seoLogs->count() > 0)
        <div class="page-break"></div>
        <div class="seo-logs">
            <h2 class="section-title">SEO Activity Logs</h2>
            @foreach($report->seoLogs as $log)
                <div class="seo-log">
                    <div class="seo-log-meta">
                        <strong>Date:</strong> {{ $log->date->format('F j, Y') }}
                    </div>
                    <div class="seo-log-content">
                        {!! $log->content['content'] ?? '' !!}
                    </div>
                </div>
            @endforeach
        </div>
    @endif
</body>
</html> 