@php
use App\Models\Report;
@endphp

<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between items-center">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ $report->title }}
            </h2>
            <div class="flex items-center space-x-4">
                <a href="{{ route('reports.pdf', $report) }}" 
                   class="inline-flex items-center px-4 py-2 bg-red-500 hover:bg-red-600 text-white rounded-md font-semibold text-sm transition-colors duration-200">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                    </svg>
                    {{ __('Download PDF') }}
                </a>
                <a href="{{ route('projects.show', $report->project) }}" 
                   class="inline-flex items-center px-4 py-2 bg-gray-500 hover:bg-gray-600 text-white rounded-md font-semibold text-sm transition-colors duration-200">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 17l-5-5m0 0l5-5m-5 5h12" />
                    </svg>
                    {{ __('Back to Project') }}
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <!-- Report Header -->
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <h3 class="text-lg font-medium text-gray-900">{{ __('Report Information') }}</h3>
                            <dl class="mt-4 space-y-4">
                                <div>
                                    <dt class="text-sm font-medium text-gray-500">{{ __('Project') }}</dt>
                                    <dd class="mt-1 text-sm text-gray-900">
                                        <a href="{{ route('projects.show', $report->project) }}" class="text-indigo-600 hover:text-indigo-900">
                                            {{ $report->project->name }}
                                        </a>
                                    </dd>
                                </div>
                                <div>
                                    <dt class="text-sm font-medium text-gray-500">{{ __('Generated By') }}</dt>
                                    <dd class="mt-1 text-sm text-gray-900">{{ $report->generatedBy->name }}</dd>
                                </div>
                                <div>
                                    <dt class="text-sm font-medium text-gray-500">{{ __('Generated At') }}</dt>
                                    <dd class="mt-1 text-sm text-gray-900">{{ $report->generated_at->format('F j, Y g:i A') }}</dd>
                                </div>
                            </dl>
                        </div>
                        <div>
                            <h3 class="text-lg font-medium text-gray-900">{{ __('Description') }}</h3>
                            <div class="mt-4 prose max-w-none">
                                {!! $report->description['content'] ?? '' !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Report Sections -->
            @foreach($report->sections->sortBy('order') as $section)
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-medium text-gray-900 mb-4">{{ $section->title }}</h3>
                    <div class="prose max-w-none">
                        {!! $section->content['content'] ?? '' !!}
                    </div>
                    @if($section->getFirstMediaUrl('section_images'))
                        <div class="mt-4">
                            <img src="{{ $section->getFirstMediaUrl('section_images') }}" 
                                 alt="{{ $section->title }}" 
                                 class="rounded-lg shadow-md">
                        </div>
                    @endif
                </div>
            </div>
            @endforeach

            <!-- SEO Logs -->
            @if($report->seoLogs->count() > 0)
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-lg font-medium text-gray-900 mb-4">{{ __('Related SEO Logs') }}</h3>
                    <div class="space-y-6">
                        @foreach($report->seoLogs->sortByDesc('date') as $log)
                            <div class="border-l-4 border-indigo-500 pl-4">
                                <div class="flex justify-between items-start">
                                    <div>
                                        <h4 class="text-base font-medium text-gray-900">{{ $log->title }}</h4>
                                        <p class="mt-1 text-sm text-gray-600">
                                            {{ $log->date->format('F j, Y') }} • {{ $log->log_type }}
                                        </p>
                                    </div>
                                    <a href="{{ route('seo-logs.show', $log) }}" 
                                       class="text-sm text-indigo-600 hover:text-indigo-900">
                                        {{ __('View Details') }}
                                    </a>
                                </div>
                                <div class="mt-2 prose prose-sm max-w-none">
                                    {!! $log->content['content'] ?? '' !!}
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            @endif
        </div>
    </div>
</x-app-layout> 